// https://zenquotes.io
// I'm not paying for their api key so it'll have to be static content this time!
export const quotes = [
  {
    q: "Not until we are lost do we begin to understand ourselves.",
    a: "Henry David Thoreau",
    c: "58",
    h: "<blockquote>&ldquo;Not until we are lost do we begin to understand ourselves.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic. ",
    a: "Charles Swindoll",
    c: "100",
    h: "<blockquote>&ldquo;When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic. &rdquo; &mdash; <footer>Charles Swindoll</footer></blockquote>",
  },
  {
    q: "It's wise to tell the truth. It's even wiser to tell it kindly.",
    a: "Maxime Lagace",
    c: "63",
    h: "<blockquote>&ldquo;It's wise to tell the truth. It's even wiser to tell it kindly.&rdquo; &mdash; <footer>Maxime Lagace</footer></blockquote>",
  },
  {
    q: "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any.",
    a: "Thomas Jefferson",
    c: "109",
    h: "<blockquote>&ldquo;Determine never to be idle. No person will have occasion to complain of the want of time who never loses any.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "If you've made a mistake, it's better just to laugh at it.",
    a: "Zen Proverb",
    c: "58",
    h: "<blockquote>&ldquo;If you've made a mistake, it's better just to laugh at it.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "Discipline yourself, and others won't need to.",
    a: "John Wooden",
    c: "46",
    h: "<blockquote>&ldquo;Discipline yourself, and others won't need to.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "To forget the whole world is easy; to make the whole world forget you is hard.",
    a: "Zhuangzi",
    c: "78",
    h: "<blockquote>&ldquo;To forget the whole world is easy; to make the whole world forget you is hard.&rdquo; &mdash; <footer>Zhuangzi</footer></blockquote>",
  },
  {
    q: "There are no mistakes in life, only lessons.",
    a: "Robin Sharma",
    c: "44",
    h: "<blockquote>&ldquo;There are no mistakes in life, only lessons.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Loving thoughts and actions are clearly beneficial for our physical and mental health.",
    a: "Dalai Lama",
    c: "86",
    h: "<blockquote>&ldquo;Loving thoughts and actions are clearly beneficial for our physical and mental health.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "The major difference between the big shot and the little shot is the big shot is just a little shot who kept on shooting.",
    a: "Zig Ziglar",
    c: "121",
    h: "<blockquote>&ldquo;The major difference between the big shot and the little shot is the big shot is just a little shot who kept on shooting.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "I succeeded by saying what everyone else is thinking.",
    a: "Joan Rivers",
    c: "53",
    h: "<blockquote>&ldquo;I succeeded by saying what everyone else is thinking.&rdquo; &mdash; <footer>Joan Rivers</footer></blockquote>",
  },
  {
    q: "To be heroic is to be courageous enough to die for something; to be inspirational is to be crazy enough to live a little.",
    a: "Criss Jami",
    c: "121",
    h: "<blockquote>&ldquo;To be heroic is to be courageous enough to die for something; to be inspirational is to be crazy enough to live a little.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "In order to be walked over, you have to be lying down.",
    a: "Celestine Chua",
    c: "54",
    h: "<blockquote>&ldquo;In order to be walked over, you have to be lying down.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "Because a thing seems difficult for you, do not think it impossible.",
    a: "Marcus Aurelius",
    c: "68",
    h: "<blockquote>&ldquo;Because a thing seems difficult for you, do not think it impossible.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "Dreams provide nourishment for the soul, just as a meal does for the body.",
    a: "Paulo Coelho",
    c: "74",
    h: "<blockquote>&ldquo;Dreams provide nourishment for the soul, just as a meal does for the body.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    a: "Bhagavad Gita",
    c: "97",
    h: "<blockquote>&ldquo;When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.&rdquo; &mdash; <footer>Bhagavad Gita</footer></blockquote>",
  },
  {
    q: "The best teacher is experience and not through someone's distorted point of view.",
    a: "Jack Kerouac",
    c: "81",
    h: "<blockquote>&ldquo;The best teacher is experience and not through someone's distorted point of view.&rdquo; &mdash; <footer>Jack Kerouac</footer></blockquote>",
  },
  {
    q: "Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along. ",
    a: "Paramahansa Yogananda",
    c: "104",
    h: "<blockquote>&ldquo;Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along. &rdquo; &mdash; <footer>Paramahansa Yogananda</footer></blockquote>",
  },
  {
    q: "It's very important to like the people you work with, otherwise life and your job is gonna be quite miserable.",
    a: "Elon Musk",
    c: "110",
    h: "<blockquote>&ldquo;It's very important to like the people you work with, otherwise life and your job is gonna be quite miserable.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "Without the rain there would be no rainbow.",
    a: "Gilbert Chesterton",
    c: "43",
    h: "<blockquote>&ldquo;Without the rain there would be no rainbow.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "There are three classes of people: those who see. Those who see when they are shown. Those who do not see.",
    a: "Leonardo da Vinci",
    c: "106",
    h: "<blockquote>&ldquo;There are three classes of people: those who see. Those who see when they are shown. Those who do not see.&rdquo; &mdash; <footer>Leonardo da Vinci</footer></blockquote>",
  },
  {
    q: "No man can get rich himself unless he enriches others.",
    a: "Earl Nightingale",
    c: "54",
    h: "<blockquote>&ldquo;No man can get rich himself unless he enriches others.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: "You can have it all. You just can't have it all at once. ",
    a: "Oprah Winfrey",
    c: "57",
    h: "<blockquote>&ldquo;You can have it all. You just can't have it all at once. &rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "To do great work one must be very idle as well as very industrious.",
    a: "Samuel Butler",
    c: "67",
    h: "<blockquote>&ldquo;To do great work one must be very idle as well as very industrious.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
  },
  {
    q: "Wrong does not cease to be wrong because the majority share in it.",
    a: "Leo Tolstoy",
    c: "66",
    h: "<blockquote>&ldquo;Wrong does not cease to be wrong because the majority share in it.&rdquo; &mdash; <footer>Leo Tolstoy</footer></blockquote>",
  },
  {
    q: "The primary cause of unhappiness is never the situation but your thoughts about it.",
    a: "Eckhart Tolle",
    c: "83",
    h: "<blockquote>&ldquo;The primary cause of unhappiness is never the situation but your thoughts about it.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "Those who dream by day are cognizant of many things which escape those who dream only by night.",
    a: "Vincent van Gogh",
    c: "95",
    h: "<blockquote>&ldquo;Those who dream by day are cognizant of many things which escape those who dream only by night.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "People tend to complicate their own lives, as if living weren't already complicated enough.",
    a: "Carlos Ruiz Zafon",
    c: "91",
    h: "<blockquote>&ldquo;People tend to complicate their own lives, as if living weren't already complicated enough.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.",
    a: "Les Brown",
    c: "108",
    h: "<blockquote>&ldquo;Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "Instead of thinking about what you are going to do when you retire, think about how you can do that now and make a living from it.",
    a: "Celestine Chua",
    c: "130",
    h: "<blockquote>&ldquo;Instead of thinking about what you are going to do when you retire, think about how you can do that now and make a living from it.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "The big thing is to make a winning effort. I'm not obsessed with wins.",
    a: "Morgan Wootten",
    c: "70",
    h: "<blockquote>&ldquo;The big thing is to make a winning effort. I'm not obsessed with wins.&rdquo; &mdash; <footer>Morgan Wootten</footer></blockquote>",
  },
  {
    q: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    a: "Dr. Seuss",
    c: "107",
    h: "<blockquote>&ldquo;You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.&rdquo; &mdash; <footer>Dr. Seuss</footer></blockquote>",
  },
  {
    q: "To be prepared is half the victory. ",
    a: "Miguel de Cervantes",
    c: "36",
    h: "<blockquote>&ldquo;To be prepared is half the victory. &rdquo; &mdash; <footer>Miguel de Cervantes</footer></blockquote>",
  },
  {
    q: "Do one thing every day that scares you.",
    a: "Eleanor Roosevelt",
    c: "39",
    h: "<blockquote>&ldquo;Do one thing every day that scares you.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Great things are not done by impulse, but by a series of small things brought together.",
    a: "Vincent van Gogh",
    c: "87",
    h: "<blockquote>&ldquo;Great things are not done by impulse, but by a series of small things brought together.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "As soon as you trust yourself, you will know how to live.",
    a: "Johann Wolfgang von Goethe",
    c: "57",
    h: "<blockquote>&ldquo;As soon as you trust yourself, you will know how to live.&rdquo; &mdash; <footer>Johann Wolfgang von Goethe</footer></blockquote>",
  },
  {
    q: "No one ever said life was fair. Just Eventful.",
    a: "Carol Burnett",
    c: "46",
    h: "<blockquote>&ldquo;No one ever said life was fair. Just Eventful.&rdquo; &mdash; <footer>Carol Burnett</footer></blockquote>",
  },
  {
    q: "When you reach the top of the mountain, keep climbing. ",
    a: "Zen Proverb",
    c: "55",
    h: "<blockquote>&ldquo;When you reach the top of the mountain, keep climbing. &rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "As you grow older you will discover that you have two hands. One for helping yourself, the other for helping others.",
    a: "Audrey Hepburn",
    c: "116",
    h: "<blockquote>&ldquo;As you grow older you will discover that you have two hands. One for helping yourself, the other for helping others.&rdquo; &mdash; <footer>Audrey Hepburn</footer></blockquote>",
  },
  {
    q: "The chief enemy of creativity is good sense.",
    a: "Pablo Picasso",
    c: "44",
    h: "<blockquote>&ldquo;The chief enemy of creativity is good sense.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
  {
    q: "You drown not by falling into a river, but by staying submerged in it.",
    a: "Paulo Coelho",
    c: "70",
    h: "<blockquote>&ldquo;You drown not by falling into a river, but by staying submerged in it.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "No problem can be solved from the same level of consciousness that created it.",
    a: "Albert Einstein",
    c: "78",
    h: "<blockquote>&ldquo;No problem can be solved from the same level of consciousness that created it.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "Experience is a comb which nature gives us when we are bald. ",
    a: "Chinese Proverb",
    c: "61",
    h: "<blockquote>&ldquo;Experience is a comb which nature gives us when we are bald. &rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "The mind that turns ever outward Will have no end to craving. Only the mind turned inward Will find a still-point of peace.",
    a: "Ming-Dao Deng",
    c: "123",
    h: "<blockquote>&ldquo;The mind that turns ever outward Will have no end to craving. Only the mind turned inward Will find a still-point of peace.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Family not only needs to consist of merely those whom we share blood, but also of those whom we'd give blood.",
    a: "Charles Dickens",
    c: "109",
    h: "<blockquote>&ldquo;Family not only needs to consist of merely those whom we share blood, but also of those whom we'd give blood.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Life is like riding a bicycle. To keep your balance you must keep moving.",
    a: "Albert Einstein",
    c: "73",
    h: "<blockquote>&ldquo;Life is like riding a bicycle. To keep your balance you must keep moving.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "If someone betrays you once, it's their fault; if they betray you twice, it's your fault.",
    a: "Eleanor Roosevelt",
    c: "89",
    h: "<blockquote>&ldquo;If someone betrays you once, it's their fault; if they betray you twice, it's your fault.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Success is within the reach of just about everyone.",
    a: "Lolly Daskal",
    c: "51",
    h: "<blockquote>&ldquo;Success is within the reach of just about everyone.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Unless someone truly has the power to say no, they never truly have the power to say yes.",
    a: "Dan Millman",
    c: "89",
    h: "<blockquote>&ldquo;Unless someone truly has the power to say no, they never truly have the power to say yes.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "It isn't that they can't see the solution. It is that they can't see the problem.",
    a: "Gilbert Chesterton",
    c: "81",
    h: "<blockquote>&ldquo;It isn't that they can't see the solution. It is that they can't see the problem.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
];
