// https://zenquotes.io
// I'm not paying for their api key so it'll have to be static content this time!
export const quotes = [
  {
    q: "Not until we are lost do we begin to understand ourselves.",
    a: "Henry David Thoreau",
    c: "58",
    h: "<blockquote>&ldquo;Not until we are lost do we begin to understand ourselves.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic. ",
    a: "Charles Swindoll",
    c: "100",
    h: "<blockquote>&ldquo;When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic. &rdquo; &mdash; <footer>Charles Swindoll</footer></blockquote>",
  },
  {
    q: "It's wise to tell the truth. It's even wiser to tell it kindly.",
    a: "Maxime Lagace",
    c: "63",
    h: "<blockquote>&ldquo;It's wise to tell the truth. It's even wiser to tell it kindly.&rdquo; &mdash; <footer>Maxime Lagace</footer></blockquote>",
  },
  {
    q: "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any.",
    a: "Thomas Jefferson",
    c: "109",
    h: "<blockquote>&ldquo;Determine never to be idle. No person will have occasion to complain of the want of time who never loses any.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "If you've made a mistake, it's better just to laugh at it.",
    a: "Zen Proverb",
    c: "58",
    h: "<blockquote>&ldquo;If you've made a mistake, it's better just to laugh at it.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "Discipline yourself, and others won't need to.",
    a: "John Wooden",
    c: "46",
    h: "<blockquote>&ldquo;Discipline yourself, and others won't need to.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "To forget the whole world is easy; to make the whole world forget you is hard.",
    a: "Zhuangzi",
    c: "78",
    h: "<blockquote>&ldquo;To forget the whole world is easy; to make the whole world forget you is hard.&rdquo; &mdash; <footer>Zhuangzi</footer></blockquote>",
  },
  {
    q: "There are no mistakes in life, only lessons.",
    a: "Robin Sharma",
    c: "44",
    h: "<blockquote>&ldquo;There are no mistakes in life, only lessons.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Loving thoughts and actions are clearly beneficial for our physical and mental health.",
    a: "Dalai Lama",
    c: "86",
    h: "<blockquote>&ldquo;Loving thoughts and actions are clearly beneficial for our physical and mental health.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "The major difference between the big shot and the little shot is the big shot is just a little shot who kept on shooting.",
    a: "Zig Ziglar",
    c: "121",
    h: "<blockquote>&ldquo;The major difference between the big shot and the little shot is the big shot is just a little shot who kept on shooting.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "I succeeded by saying what everyone else is thinking.",
    a: "Joan Rivers",
    c: "53",
    h: "<blockquote>&ldquo;I succeeded by saying what everyone else is thinking.&rdquo; &mdash; <footer>Joan Rivers</footer></blockquote>",
  },
  {
    q: "To be heroic is to be courageous enough to die for something; to be inspirational is to be crazy enough to live a little.",
    a: "Criss Jami",
    c: "121",
    h: "<blockquote>&ldquo;To be heroic is to be courageous enough to die for something; to be inspirational is to be crazy enough to live a little.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "In order to be walked over, you have to be lying down.",
    a: "Celestine Chua",
    c: "54",
    h: "<blockquote>&ldquo;In order to be walked over, you have to be lying down.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "Because a thing seems difficult for you, do not think it impossible.",
    a: "Marcus Aurelius",
    c: "68",
    h: "<blockquote>&ldquo;Because a thing seems difficult for you, do not think it impossible.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "Dreams provide nourishment for the soul, just as a meal does for the body.",
    a: "Paulo Coelho",
    c: "74",
    h: "<blockquote>&ldquo;Dreams provide nourishment for the soul, just as a meal does for the body.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    a: "Bhagavad Gita",
    c: "97",
    h: "<blockquote>&ldquo;When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.&rdquo; &mdash; <footer>Bhagavad Gita</footer></blockquote>",
  },
  {
    q: "The best teacher is experience and not through someone's distorted point of view.",
    a: "Jack Kerouac",
    c: "81",
    h: "<blockquote>&ldquo;The best teacher is experience and not through someone's distorted point of view.&rdquo; &mdash; <footer>Jack Kerouac</footer></blockquote>",
  },
  {
    q: "Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along. ",
    a: "Paramahansa Yogananda",
    c: "104",
    h: "<blockquote>&ldquo;Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along. &rdquo; &mdash; <footer>Paramahansa Yogananda</footer></blockquote>",
  },
  {
    q: "It's very important to like the people you work with, otherwise life and your job is gonna be quite miserable.",
    a: "Elon Musk",
    c: "110",
    h: "<blockquote>&ldquo;It's very important to like the people you work with, otherwise life and your job is gonna be quite miserable.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "Without the rain there would be no rainbow.",
    a: "Gilbert Chesterton",
    c: "43",
    h: "<blockquote>&ldquo;Without the rain there would be no rainbow.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "There are three classes of people: those who see. Those who see when they are shown. Those who do not see.",
    a: "Leonardo da Vinci",
    c: "106",
    h: "<blockquote>&ldquo;There are three classes of people: those who see. Those who see when they are shown. Those who do not see.&rdquo; &mdash; <footer>Leonardo da Vinci</footer></blockquote>",
  },
  {
    q: "No man can get rich himself unless he enriches others.",
    a: "Earl Nightingale",
    c: "54",
    h: "<blockquote>&ldquo;No man can get rich himself unless he enriches others.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: "You can have it all. You just can't have it all at once. ",
    a: "Oprah Winfrey",
    c: "57",
    h: "<blockquote>&ldquo;You can have it all. You just can't have it all at once. &rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "To do great work one must be very idle as well as very industrious.",
    a: "Samuel Butler",
    c: "67",
    h: "<blockquote>&ldquo;To do great work one must be very idle as well as very industrious.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
  },
  {
    q: "Wrong does not cease to be wrong because the majority share in it.",
    a: "Leo Tolstoy",
    c: "66",
    h: "<blockquote>&ldquo;Wrong does not cease to be wrong because the majority share in it.&rdquo; &mdash; <footer>Leo Tolstoy</footer></blockquote>",
  },
  {
    q: "The primary cause of unhappiness is never the situation but your thoughts about it.",
    a: "Eckhart Tolle",
    c: "83",
    h: "<blockquote>&ldquo;The primary cause of unhappiness is never the situation but your thoughts about it.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "Those who dream by day are cognizant of many things which escape those who dream only by night.",
    a: "Vincent van Gogh",
    c: "95",
    h: "<blockquote>&ldquo;Those who dream by day are cognizant of many things which escape those who dream only by night.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "People tend to complicate their own lives, as if living weren't already complicated enough.",
    a: "Carlos Ruiz Zafon",
    c: "91",
    h: "<blockquote>&ldquo;People tend to complicate their own lives, as if living weren't already complicated enough.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.",
    a: "Les Brown",
    c: "108",
    h: "<blockquote>&ldquo;Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "Instead of thinking about what you are going to do when you retire, think about how you can do that now and make a living from it.",
    a: "Celestine Chua",
    c: "130",
    h: "<blockquote>&ldquo;Instead of thinking about what you are going to do when you retire, think about how you can do that now and make a living from it.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "The big thing is to make a winning effort. I'm not obsessed with wins.",
    a: "Morgan Wootten",
    c: "70",
    h: "<blockquote>&ldquo;The big thing is to make a winning effort. I'm not obsessed with wins.&rdquo; &mdash; <footer>Morgan Wootten</footer></blockquote>",
  },
  {
    q: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    a: "Dr. Seuss",
    c: "107",
    h: "<blockquote>&ldquo;You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.&rdquo; &mdash; <footer>Dr. Seuss</footer></blockquote>",
  },
  {
    q: "To be prepared is half the victory. ",
    a: "Miguel de Cervantes",
    c: "36",
    h: "<blockquote>&ldquo;To be prepared is half the victory. &rdquo; &mdash; <footer>Miguel de Cervantes</footer></blockquote>",
  },
  {
    q: "Do one thing every day that scares you.",
    a: "Eleanor Roosevelt",
    c: "39",
    h: "<blockquote>&ldquo;Do one thing every day that scares you.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Great things are not done by impulse, but by a series of small things brought together.",
    a: "Vincent van Gogh",
    c: "87",
    h: "<blockquote>&ldquo;Great things are not done by impulse, but by a series of small things brought together.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "As soon as you trust yourself, you will know how to live.",
    a: "Johann Wolfgang von Goethe",
    c: "57",
    h: "<blockquote>&ldquo;As soon as you trust yourself, you will know how to live.&rdquo; &mdash; <footer>Johann Wolfgang von Goethe</footer></blockquote>",
  },
  {
    q: "No one ever said life was fair. Just Eventful.",
    a: "Carol Burnett",
    c: "46",
    h: "<blockquote>&ldquo;No one ever said life was fair. Just Eventful.&rdquo; &mdash; <footer>Carol Burnett</footer></blockquote>",
  },
  {
    q: "When you reach the top of the mountain, keep climbing. ",
    a: "Zen Proverb",
    c: "55",
    h: "<blockquote>&ldquo;When you reach the top of the mountain, keep climbing. &rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "As you grow older you will discover that you have two hands. One for helping yourself, the other for helping others.",
    a: "Audrey Hepburn",
    c: "116",
    h: "<blockquote>&ldquo;As you grow older you will discover that you have two hands. One for helping yourself, the other for helping others.&rdquo; &mdash; <footer>Audrey Hepburn</footer></blockquote>",
  },
  {
    q: "The chief enemy of creativity is good sense.",
    a: "Pablo Picasso",
    c: "44",
    h: "<blockquote>&ldquo;The chief enemy of creativity is good sense.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
  {
    q: "You drown not by falling into a river, but by staying submerged in it.",
    a: "Paulo Coelho",
    c: "70",
    h: "<blockquote>&ldquo;You drown not by falling into a river, but by staying submerged in it.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "No problem can be solved from the same level of consciousness that created it.",
    a: "Albert Einstein",
    c: "78",
    h: "<blockquote>&ldquo;No problem can be solved from the same level of consciousness that created it.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "Experience is a comb which nature gives us when we are bald. ",
    a: "Chinese Proverb",
    c: "61",
    h: "<blockquote>&ldquo;Experience is a comb which nature gives us when we are bald. &rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "The mind that turns ever outward Will have no end to craving. Only the mind turned inward Will find a still-point of peace.",
    a: "Ming-Dao Deng",
    c: "123",
    h: "<blockquote>&ldquo;The mind that turns ever outward Will have no end to craving. Only the mind turned inward Will find a still-point of peace.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Family not only needs to consist of merely those whom we share blood, but also of those whom we'd give blood.",
    a: "Charles Dickens",
    c: "109",
    h: "<blockquote>&ldquo;Family not only needs to consist of merely those whom we share blood, but also of those whom we'd give blood.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Life is like riding a bicycle. To keep your balance you must keep moving.",
    a: "Albert Einstein",
    c: "73",
    h: "<blockquote>&ldquo;Life is like riding a bicycle. To keep your balance you must keep moving.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "If someone betrays you once, it's their fault; if they betray you twice, it's your fault.",
    a: "Eleanor Roosevelt",
    c: "89",
    h: "<blockquote>&ldquo;If someone betrays you once, it's their fault; if they betray you twice, it's your fault.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Success is within the reach of just about everyone.",
    a: "Lolly Daskal",
    c: "51",
    h: "<blockquote>&ldquo;Success is within the reach of just about everyone.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Unless someone truly has the power to say no, they never truly have the power to say yes.",
    a: "Dan Millman",
    c: "89",
    h: "<blockquote>&ldquo;Unless someone truly has the power to say no, they never truly have the power to say yes.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "It isn't that they can't see the solution. It is that they can't see the problem.",
    a: "Gilbert Chesterton",
    c: "81",
    h: "<blockquote>&ldquo;It isn't that they can't see the solution. It is that they can't see the problem.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "Investing in yourself is the best investment you will ever make.",
    a: "Robin Sharma",
    c: "64",
    h: "<blockquote>&ldquo;Investing in yourself is the best investment you will ever make.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.",
    a: "Sigmund Freud",
    c: "130",
    h: "<blockquote>&ldquo;Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "There are no constraints on the human mind, no walls around the human spirit, no barriers to our progress except those we ourselves erect.",
    a: "Ronald Reagan",
    c: "138",
    h: "<blockquote>&ldquo;There are no constraints on the human mind, no walls around the human spirit, no barriers to our progress except those we ourselves erect.&rdquo; &mdash; <footer>Ronald Reagan</footer></blockquote>",
  },
  {
    q: "What one does is what counts. Not what one had the intention of doing.",
    a: "Pablo Picasso",
    c: "70",
    h: "<blockquote>&ldquo;What one does is what counts. Not what one had the intention of doing.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
  {
    q: "Everyday you can take a tiny step in the right direction.",
    a: "Unknown",
    c: "57",
    h: "<blockquote>&ldquo;Everyday you can take a tiny step in the right direction.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Sorrow is how we learn to love.",
    a: "Rita Mae Brown",
    c: "31",
    h: "<blockquote>&ldquo;Sorrow is how we learn to love.&rdquo; &mdash; <footer>Rita Mae Brown</footer></blockquote>",
  },
  {
    q: "The power of human thought grows exponentially with the number of minds that share that thought.",
    a: "Dan Brown",
    c: "96",
    h: "<blockquote>&ldquo;The power of human thought grows exponentially with the number of minds that share that thought.&rdquo; &mdash; <footer>Dan Brown</footer></blockquote>",
  },
  {
    q: "Winning isn't everything, but wanting to win is.",
    a: "Vince Lombardi",
    c: "48",
    h: "<blockquote>&ldquo;Winning isn't everything, but wanting to win is.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
  },
  {
    q: "Be gentle with yourself. Think less and feel more. Be as happy as you can. You only have this moment.",
    a: "Dan Millman",
    c: "101",
    h: "<blockquote>&ldquo;Be gentle with yourself. Think less and feel more. Be as happy as you can. You only have this moment.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "Courage is the price that life exacts for granting peace.",
    a: "Amelia Earhart",
    c: "57",
    h: "<blockquote>&ldquo;Courage is the price that life exacts for granting peace.&rdquo; &mdash; <footer>Amelia Earhart</footer></blockquote>",
  },
  {
    q: "Changing minds is harder than finding people who already agree.",
    a: "Jack Butcher",
    c: "63",
    h: "<blockquote>&ldquo;Changing minds is harder than finding people who already agree.&rdquo; &mdash; <footer>Jack Butcher</footer></blockquote>",
  },
  {
    q: "The best way to predict your future is to create it.",
    a: "Abraham Lincoln",
    c: "52",
    h: "<blockquote>&ldquo;The best way to predict your future is to create it.&rdquo; &mdash; <footer>Abraham Lincoln</footer></blockquote>",
  },
  {
    q: "The older you get, the better you get. Unless you're a banana.",
    a: "Betty White",
    c: "62",
    h: "<blockquote>&ldquo;The older you get, the better you get. Unless you're a banana.&rdquo; &mdash; <footer>Betty White</footer></blockquote>",
  },
  {
    q: "Our truest life is when we are in dreams awake.",
    a: "Henry David Thoreau",
    c: "47",
    h: "<blockquote>&ldquo;Our truest life is when we are in dreams awake.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "Nothing can bring you peace but yourself.",
    a: "Dale Carnegie",
    c: "41",
    h: "<blockquote>&ldquo;Nothing can bring you peace but yourself.&rdquo; &mdash; <footer>Dale Carnegie</footer></blockquote>",
  },
  {
    q: "If we know how to adapt, we end up being superior.",
    a: "Ming-Dao Deng",
    c: "50",
    h: "<blockquote>&ldquo;If we know how to adapt, we end up being superior.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Be polite to all, but intimate with few.",
    a: "Thomas Jefferson",
    c: "40",
    h: "<blockquote>&ldquo;Be polite to all, but intimate with few.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "You can only be afraid of what you think you know.",
    a: "Jiddu Krishnamurti",
    c: "50",
    h: "<blockquote>&ldquo;You can only be afraid of what you think you know.&rdquo; &mdash; <footer>Jiddu Krishnamurti</footer></blockquote>",
  },
  {
    q: "Our attitude toward life determines life's attitude towards us.",
    a: "Earl Nightingale",
    c: "63",
    h: "<blockquote>&ldquo;Our attitude toward life determines life's attitude towards us.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: "Trust, like the soul, never returns once it is gone.",
    a: "Publilius Syrus",
    c: "52",
    h: "<blockquote>&ldquo;Trust, like the soul, never returns once it is gone.&rdquo; &mdash; <footer>Publilius Syrus</footer></blockquote>",
  },
  {
    q: "Where there's life, there's hope.",
    a: "Stephen Hawking",
    c: "33",
    h: "<blockquote>&ldquo;Where there's life, there's hope.&rdquo; &mdash; <footer>Stephen Hawking</footer></blockquote>",
  },
  {
    q: "Success is built sequentially. It's one thing at a time.",
    a: "Gary Keller",
    c: "56",
    h: "<blockquote>&ldquo;Success is built sequentially. It's one thing at a time.&rdquo; &mdash; <footer>Gary Keller</footer></blockquote>",
  },
  {
    q: "If it is not right, do not do it, if it is not true, do not say it.",
    a: "Marcus Aurelius",
    c: "67",
    h: "<blockquote>&ldquo;If it is not right, do not do it, if it is not true, do not say it.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "Even a hare will bite when it is cornered. ",
    a: "Chinese Proverb",
    c: "43",
    h: "<blockquote>&ldquo;Even a hare will bite when it is cornered. &rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "Only he who has no use for the empire is fit to be entrusted with it.",
    a: "Zhuangzi",
    c: "69",
    h: "<blockquote>&ldquo;Only he who has no use for the empire is fit to be entrusted with it.&rdquo; &mdash; <footer>Zhuangzi</footer></blockquote>",
  },
  {
    q: "I admire those who do good and expect nothing in return.",
    a: "Roy T. Bennett",
    c: "56",
    h: "<blockquote>&ldquo;I admire those who do good and expect nothing in return.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Nothing has any power over me other than that which I give it through my conscious thoughts.",
    a: "Tony Robbins",
    c: "92",
    h: "<blockquote>&ldquo;Nothing has any power over me other than that which I give it through my conscious thoughts.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "Never confuse a single defeat with a final defeat.",
    a: "F. Scott Fitzgerald",
    c: "50",
    h: "<blockquote>&ldquo;Never confuse a single defeat with a final defeat.&rdquo; &mdash; <footer>F. Scott Fitzgerald</footer></blockquote>",
  },
  {
    q: "When you know what you want, and want it bad enough, you will find a way to get it.",
    a: "Jim Rohn",
    c: "83",
    h: "<blockquote>&ldquo;When you know what you want, and want it bad enough, you will find a way to get it.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "The most efficient way of rendering the poor harmless is to teach them to want to imitate the rich.",
    a: "Carlos Ruiz Zafon",
    c: "99",
    h: "<blockquote>&ldquo;The most efficient way of rendering the poor harmless is to teach them to want to imitate the rich.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "An un-examined life is not worth living.",
    a: "Socrates",
    c: "40",
    h: "<blockquote>&ldquo;An un-examined life is not worth living.&rdquo; &mdash; <footer>Socrates</footer></blockquote>",
  },
  {
    q: "Instead of worrying about what you cannot control, shift your energy to what you can create.",
    a: "Roy T. Bennett",
    c: "92",
    h: "<blockquote>&ldquo;Instead of worrying about what you cannot control, shift your energy to what you can create.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Always keep your eyes open. Keep watching. Because whatever you see can inspire you.",
    a: "Grace Coddington",
    c: "84",
    h: "<blockquote>&ldquo;Always keep your eyes open. Keep watching. Because whatever you see can inspire you.&rdquo; &mdash; <footer>Grace Coddington</footer></blockquote>",
  },
  {
    q: "Unless a man is master of his soul, all other kinds of mastery amount to little.",
    a: "Theodore Roosevelt",
    c: "80",
    h: "<blockquote>&ldquo;Unless a man is master of his soul, all other kinds of mastery amount to little.&rdquo; &mdash; <footer>Theodore Roosevelt</footer></blockquote>",
  },
  {
    q: "Everybody by your side ain't on your side.",
    a: "Steve Harvey",
    c: "42",
    h: "<blockquote>&ldquo;Everybody by your side ain't on your side.&rdquo; &mdash; <footer>Steve Harvey</footer></blockquote>",
  },
  {
    q: "Every artist dips his brush in his own soul, and paints his own nature into his pictures.",
    a: "Henry Ward Beecher",
    c: "89",
    h: "<blockquote>&ldquo;Every artist dips his brush in his own soul, and paints his own nature into his pictures.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
  },
  {
    q: "Gratitude is the fairest blossom which springs from the soul.",
    a: "Henry Ward Beecher",
    c: "61",
    h: "<blockquote>&ldquo;Gratitude is the fairest blossom which springs from the soul.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
  },
  {
    q: "Show kindness but never expect it. Show authenticity but never expect it. Only the wise are indifferent to things they can't control.",
    a: "Maxime Lagace",
    c: "133",
    h: "<blockquote>&ldquo;Show kindness but never expect it. Show authenticity but never expect it. Only the wise are indifferent to things they can't control.&rdquo; &mdash; <footer>Maxime Lagace</footer></blockquote>",
  },
  {
    q: "There is a cosmic law which says that every satisfaction must be paid for with a dissatisfaction.",
    a: "G.I. Gurdjieff",
    c: "97",
    h: "<blockquote>&ldquo;There is a cosmic law which says that every satisfaction must be paid for with a dissatisfaction.&rdquo; &mdash; <footer>G.I. Gurdjieff</footer></blockquote>",
  },
  {
    q: "The more we value things, the less we value ourselves.  ",
    a: "Bruce Lee",
    c: "56",
    h: "<blockquote>&ldquo;The more we value things, the less we value ourselves.  &rdquo; &mdash; <footer>Bruce Lee</footer></blockquote>",
  },
  {
    q: "When the time is gone, you can never get it back.",
    a: "Stephen King",
    c: "49",
    h: "<blockquote>&ldquo;When the time is gone, you can never get it back.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "We learn by pushing ourselves and finding what really lies at the outer reaches of our abilities.",
    a: "Josh Waitzkin",
    c: "97",
    h: "<blockquote>&ldquo;We learn by pushing ourselves and finding what really lies at the outer reaches of our abilities.&rdquo; &mdash; <footer>Josh Waitzkin</footer></blockquote>",
  },
  {
    q: "The whole of life, from the moment you are born to the moment you die, is a process of learning.",
    a: "Jiddu Krishnamurti",
    c: "96",
    h: "<blockquote>&ldquo;The whole of life, from the moment you are born to the moment you die, is a process of learning.&rdquo; &mdash; <footer>Jiddu Krishnamurti</footer></blockquote>",
  },
  {
    q: "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.",
    a: "Mark Twain",
    c: "98",
    h: "<blockquote>&ldquo;If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "The only place where success comes before work is in the dictionary.",
    a: "Vidal Sassoon",
    c: "68",
    h: "<blockquote>&ldquo;The only place where success comes before work is in the dictionary.&rdquo; &mdash; <footer>Vidal Sassoon</footer></blockquote>",
  },
  {
    q: "Conscience is a man's compass. ",
    a: "Vincent van Gogh",
    c: "31",
    h: "<blockquote>&ldquo;Conscience is a man's compass. &rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "You must learn to let go. Release the stress. You were never in control anyway.",
    a: "Steve Maraboli",
    c: "79",
    h: "<blockquote>&ldquo;You must learn to let go. Release the stress. You were never in control anyway.&rdquo; &mdash; <footer>Steve Maraboli</footer></blockquote>",
  },
  {
    q: "A clear conscience is the sure sign of a bad memory.",
    a: "Mark Twain",
    c: "52",
    h: "<blockquote>&ldquo;A clear conscience is the sure sign of a bad memory.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    a: "Marcus Aurelius",
    c: "95",
    h: "<blockquote>&ldquo;Very little is needed to make a happy life; it is all within yourself, in your way of thinking.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "Never close your lips to those whom you have already opened your heart.",
    a: "Charles Dickens",
    c: "71",
    h: "<blockquote>&ldquo;Never close your lips to those whom you have already opened your heart.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
];
